### ISSUE TITLE
Link to docs not working

### ISSUE THREAD

**Issue by davibarreira** [chriselrod/FunctionWrappersWrappers.jl#2]
Link to docs not working.

**Comment by CarloLucibello** [comment]
still not working

**Comment by CarloLucibello** [comment]
Since this package is registered in the General Registry, maybe it is worth adding a few lines to the readme explaining what it does (and honestly I am surprised that a package providing no explanation at all of its purpose got registered)

**Comment by chriselrod** [comment]
> and honestly I am surprised that a package providing no explanation at all of its purpose got registered

Documentation or not, it is probably used more heavily throughout the ecosystem than most registered packages:
https://juliahub.com/ui/Packages/FunctionWrappersWrappers/e68Y1/0.1.3?page=2

FunctionWrappers supports only one set of input->return types. This library provides a wrapper holding multiple FunctionWrappers with different input types, and lets you dispatch to matching input types.
You can look at the tests if you want an example: https://github.com/SciML/FunctionWrappersWrappers.jl/blob/main/test/runtests.jl
